version: '3.0'

services:
  app:
    container_name: lesson_20240828_app
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      PASSWORD_SALT: qwerty
      DATABASE_USERNAME: db_user
      DATABASE_PASSWORD: db_pass
      DATABASE_DB: app
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_CONNECTION: pgsql

  webserver:
    container_name: lesson_20240828_webserver
    build:
      context: .
      dockerfile: .docker/webserver/Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8080:80" 

  db:
    container_name: lesson_20240828_db
    image: 'bitnami/postgresql:15.0.0'
    volumes:
      - 'db_data:/bitnami/postgresql'
    environment:
      POSTGRESQL_USERNAME: db_user
      POSTGRESQL_PASSWORD: db_pass
      POSTGRESQL_DATABASE: app

volumes:
  db_data:
        
